"""SQL knowledge layer -> markdown materializer.

Renders one markdown file per (strategy, universe) under <out_dir>/strategies/,
plus a top-level overview.md and contradictions.jsonl.  Idempotent -- re-runs
produce byte-identical output when the underlying SQL data is unchanged
(useful for committing the output and diffing in PRs).

What this module does NOT do:
  - Vendor llm-wiki-agent.  The plan explicitly says "if synthesis isn't
    adding value over the SQL views, kill this phase."  The materializer is
    deliberately a thin view layer; vendoring the external agent is a
    separate operator decision.
  - Mutate any DB state.  Pure read-only over the SQL knowledge layer.

Inputs (read-only):
  v_strategy_summary, v_open_contradictions, strategy_lifecycle_history,
  journal_mirror (when populated).

Outputs:
  <out_dir>/overview.md
  <out_dir>/strategies/<strategy>__<universe>.md
  <out_dir>/contradictions.jsonl
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

logger = logging.getLogger(__name__)

DEFAULT_OUT_DIR = Path(__file__).resolve().parent
# Recent-events window for the per-strategy timeline.
RECENT_LIFECYCLE_LIMIT = 10
RECENT_JOURNAL_LIMIT = 10


@dataclass
class MaterializeResult:
    out_dir: Path
    strategies_rendered: int
    contradictions_emitted: int
    files_written: List[str]


def _slugify(s: str) -> str:
    """Filesystem-safe slug for strategy/universe names."""
    if not s:
        return "unknown"
    cleaned = re.sub(r"[^a-zA-Z0-9._-]+", "_", s).strip("_")
    return cleaned or "unknown"


def _fmt_num(v: Any, places: int = 3) -> str:
    if v is None:
        return "—"
    try:
        return f"{float(v):.{places}f}"
    except (TypeError, ValueError):
        return str(v)


def _fmt_pct(v: Any) -> str:
    if v is None:
        return "—"
    try:
        return f"{float(v):.2f}%"
    except (TypeError, ValueError):
        return str(v)


# ── Pure renderers (no SQL inside) ───────────────────────────────────────────

def render_strategy_md(
    summary: Dict[str, Any],
    contradictions: List[Dict[str, Any]],
    lifecycle: List[Dict[str, Any]],
    journal: List[Dict[str, Any]],
) -> str:
    """Build the markdown for one (strategy, universe) row."""
    strategy = summary.get("strategy", "?")
    universe = summary.get("universe", "?")

    head_lines = [
        f"# {strategy} @ {universe}",
        "",
        f"_Generated by atlas wiki materializer. Source of truth: SQL knowledge layer._",
        "",
        "## Measured (research_best)",
        "",
        f"| metric | value |",
        f"| --- | --- |",
        f"| solo_sharpe | {_fmt_num(summary.get('solo_sharpe'))} |",
        f"| portfolio_sharpe | {_fmt_num(summary.get('portfolio_sharpe'))} |",
        f"| max_dd_pct | {_fmt_pct(summary.get('max_dd_pct'))} |",
        f"| trades | {summary.get('trades') if summary.get('trades') is not None else '—'} |",
        f"| last_measured_at | {summary.get('last_measured_at') or '—'} |",
        f"| lifecycle_state | {summary.get('lifecycle_state') or '—'} |",
        f"| active_claims | {summary.get('active_claims') or 0} |",
        f"| open_contradictions | {summary.get('open_contradictions') or 0} |",
        "",
    ]

    if contradictions:
        cont_lines = [
            "## Open Contradictions (paper claim ≠ measured)",
            "",
            "| severity | metric | claimed | measured | Δ | source |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for c in contradictions:
            src = c.get("source_title") or c.get("source_id") or "?"
            url = c.get("source_url")
            src_md = f"[{src}]({url})" if url else src
            cont_lines.append(
                f"| {c.get('severity')} | {c.get('metric')} | "
                f"{_fmt_num(c.get('claimed_value'), 2)} | "
                f"{_fmt_num(c.get('measured_value'), 2)} | "
                f"{_fmt_num(c.get('delta'), 2)} | {src_md} |"
            )
        cont_lines.append("")
    else:
        cont_lines = ["## Open Contradictions", "", "_None._", ""]

    lc_lines = ["## Recent Lifecycle Transitions", ""]
    if lifecycle:
        lc_lines.extend([
            "| at | from | to | operator | reason |",
            "| --- | --- | --- | --- | --- |",
        ])
        for ev in lifecycle:
            lc_lines.append(
                f"| {ev.get('transitioned_at') or '—'} | "
                f"{ev.get('from_state') or '—'} | "
                f"{ev.get('to_state') or '—'} | "
                f"{ev.get('operator') or '—'} | "
                f"{(ev.get('reason') or '—')[:120]} |"
            )
    else:
        lc_lines.append("_No transitions on file._")
    lc_lines.append("")

    j_lines = ["## Recent Journal Entries", ""]
    if journal:
        j_lines.extend([
            "| ts | verdict | sharpe | trades | learnings |",
            "| --- | --- | --- | --- | --- |",
        ])
        for e in journal:
            km = e.get("key_metrics") or {}
            learnings = e.get("learnings") or []
            learnings_str = "; ".join(str(l) for l in learnings[:2])[:160]
            j_lines.append(
                f"| {e.get('timestamp') or '—'} | "
                f"{e.get('verdict') or '—'} | "
                f"{_fmt_num(km.get('sharpe'), 2) if isinstance(km, dict) else '—'} | "
                f"{(km.get('trades') if isinstance(km, dict) else None) or '—'} | "
                f"{learnings_str} |"
            )
    else:
        j_lines.append("_No journal entries on file._")
    j_lines.append("")

    return "\n".join(head_lines + cont_lines + lc_lines + j_lines).rstrip() + "\n"


def render_overview_md(
    summaries: List[Dict[str, Any]],
    open_contradiction_count: int,
) -> str:
    n_strats = len(summaries)
    n_with_contradictions = sum(
        1 for s in summaries if (s.get("open_contradictions") or 0) > 0
    )
    by_state: Dict[str, int] = {}
    for s in summaries:
        state = s.get("lifecycle_state") or "UNKNOWN"
        by_state[state] = by_state.get(state, 0) + 1

    lines = [
        "# Atlas Research — Wiki Overview",
        "",
        "_Auto-generated from the SQL knowledge layer. "
        "See per-strategy pages under `strategies/`._",
        "",
        "## Counts",
        "",
        f"- Strategies tracked: **{n_strats}**",
        f"- Strategies with open contradictions: **{n_with_contradictions}**",
        f"- Total open contradictions: **{open_contradiction_count}**",
        "",
        "## By Lifecycle State",
        "",
        "| state | n |",
        "| --- | --- |",
    ]
    for state in sorted(by_state):
        lines.append(f"| {state} | {by_state[state]} |")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_contradictions_jsonl(contradictions: List[Dict[str, Any]]) -> str:
    """One line per contradiction, deterministic ordering for stable diffs."""
    out_lines: List[str] = []
    # Stable sort: severity (critical→major→minor), then |delta| DESC, then claim_id.
    sev_rank = {"critical": 0, "major": 1, "minor": 2}
    rows = sorted(
        contradictions,
        key=lambda c: (
            sev_rank.get(c.get("severity", "minor"), 9),
            -float(c.get("delta_abs") or 0.0),
            str(c.get("claim_id") or ""),
        ),
    )
    for c in rows:
        compact = {
            "contradiction_id": c.get("contradiction_id"),
            "claim_id": c.get("claim_id"),
            "strategy": c.get("strategy"),
            "universe": c.get("universe"),
            "metric": c.get("metric"),
            "claimed_value": c.get("claimed_value"),
            "measured_value": c.get("measured_value"),
            "delta": c.get("delta"),
            "severity": c.get("severity"),
            "first_seen_at": c.get("first_seen_at"),
            "source_id": c.get("source_id"),
            "source_title": c.get("source_title"),
            "source_url": c.get("source_url"),
        }
        out_lines.append(json.dumps(compact, sort_keys=True))
    return "\n".join(out_lines) + ("\n" if out_lines else "")


# ── SQL readers (one read per call; never mutates) ───────────────────────────

def _read_all_summaries() -> List[Dict[str, Any]]:
    from db.atlas_db import get_db
    with get_db() as conn:
        rows = conn.execute(
            "SELECT * FROM v_strategy_summary "
            "ORDER BY strategy, universe"
        ).fetchall()
        return [dict(r) for r in rows]


def _read_open_contradictions_for(strategy: str) -> List[Dict[str, Any]]:
    from db.knowledge import get_open_contradictions
    return get_open_contradictions(strategy=strategy, limit=50)


def _read_all_open_contradictions() -> List[Dict[str, Any]]:
    from db.knowledge import get_open_contradictions
    return get_open_contradictions(limit=10_000)


def _read_recent_lifecycle(strategy: str, universe: str) -> List[Dict[str, Any]]:
    from db.atlas_db import get_db
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT * FROM strategy_lifecycle_history
            WHERE strategy = ? AND universe = ?
            ORDER BY transitioned_at DESC, id DESC
            LIMIT ?
            """,
            (strategy, universe, RECENT_LIFECYCLE_LIMIT),
        ).fetchall()
        return [dict(r) for r in rows]


def _read_recent_journal(strategy: str) -> List[Dict[str, Any]]:
    """Read recent journal_mirror rows when the dual-write table is populated.

    Returns [] if journal_mirror has no rows for this strategy -- the JSON
    journal remains canonical until Phase 6 completes the cutover.
    """
    from db.knowledge import list_journal_mirror_rows
    try:
        return list_journal_mirror_rows(strategy=strategy, limit=RECENT_JOURNAL_LIMIT)
    except Exception:  # noqa: BLE001 -- defensive
        return []


# ── Driver ───────────────────────────────────────────────────────────────────

def materialize(
    out_dir: Optional[Path] = None,
    *,
    write: bool = True,
) -> MaterializeResult:
    """Render the entire wiki tree.  Returns a summary of what was generated.

    Args:
        out_dir:  Target directory.  Defaults to research/wiki/ (this package's
                  own directory).
        write:    When False, skip filesystem writes -- useful for dry-runs.
    """
    target = (out_dir or DEFAULT_OUT_DIR).resolve()
    strategies_dir = target / "strategies"

    summaries = _read_all_summaries()
    open_contradictions = _read_all_open_contradictions()

    files_written: List[str] = []

    if write:
        strategies_dir.mkdir(parents=True, exist_ok=True)

    # Per-strategy markdown
    for summary in summaries:
        strategy = summary.get("strategy") or "unknown"
        universe = summary.get("universe") or "unknown"
        slug = f"{_slugify(strategy)}__{_slugify(universe)}.md"

        strat_contradictions = [
            c for c in open_contradictions
            if c.get("strategy") == strategy and c.get("universe") == universe
        ]
        lifecycle = _read_recent_lifecycle(strategy, universe)
        journal = _read_recent_journal(strategy)

        md = render_strategy_md(summary, strat_contradictions, lifecycle, journal)
        path = strategies_dir / slug
        files_written.append(str(path.relative_to(target)))
        if write:
            path.write_text(md, encoding="utf-8")

    # Overview
    overview_md = render_overview_md(summaries, len(open_contradictions))
    overview_path = target / "overview.md"
    files_written.append(str(overview_path.relative_to(target)))
    if write:
        overview_path.write_text(overview_md, encoding="utf-8")

    # Contradictions JSONL
    cj = render_contradictions_jsonl(open_contradictions)
    cj_path = target / "contradictions.jsonl"
    files_written.append(str(cj_path.relative_to(target)))
    if write:
        cj_path.write_text(cj, encoding="utf-8")

    return MaterializeResult(
        out_dir=target,
        strategies_rendered=len(summaries),
        contradictions_emitted=len(open_contradictions),
        files_written=sorted(files_written),
    )
