import type { AtlasJobSpec } from "./types";

export const ATLAS_JOB_CATALOG: AtlasJobSpec[] = [
  {
    name: "health_check",
    category: "health",
    summary: "Run recent-period backtest health check and write a health report JSON.",
    commandPreview: "python scripts/health_check.py",
    estimatedRuntimeSec: 300,
    reads: ["config/active_config.json", "data/cache/*.parquet"],
    writes: ["logs/health_check_YYYY-MM-DD.json"],
    artifacts: [
      {
        kind: "report_json",
        path: "logs/health_check_YYYY-MM-DD.json",
        description: "Health status, baseline comparison, degradation flags, and metrics."
      }
    ],
    approvalHint: "safe"
  },
  {
    name: "reoptimize_full_universe",
    category: "optimization",
    summary: "Coordinate-descent re-optimization across active strategies on the full cached universe.",
    commandPreview: "python scripts/reoptimize_full_universe.py",
    estimatedRuntimeSec: 7200,
    reads: ["config/active_config.json", "data/cache/*.parquet"],
    writes: ["backtest/results/reoptimization_full_universe.json", "config/*.json"],
    artifacts: [
      {
        kind: "metrics_json",
        path: "backtest/results/reoptimization_full_universe.json",
        description: "Optimization sweep results and baseline/optimized scores."
      }
    ],
    approvalHint: "high_risk"
  },
  {
    name: "validate_oos",
    category: "validation",
    summary: "Run OOS split, perturbation robustness, and walk-forward consistency validation.",
    commandPreview: "python scripts/validate_oos.py",
    estimatedRuntimeSec: 5400,
    reads: ["config/active_config.json", "data/cache/*.parquet"],
    writes: ["backtest/results/v92_oos_validation.json"],
    artifacts: [
      {
        kind: "report_json",
        path: "backtest/results/v92_oos_validation.json",
        description: "OOS metrics, perturbation trials, and walk-forward window analysis."
      }
    ],
    approvalHint: "review"
  },
  {
    name: "auto_reoptimize",
    category: "optimization",
    summary: "End-to-end health check, reoptimize, validate, compare, and restore/promote flow.",
    commandPreview: "python scripts/auto_reoptimize.py",
    estimatedRuntimeSec: 10800,
    reads: ["config/active_config.json", "logs/health_check_*.json", "backtest/results/*.json"],
    writes: ["logs/auto_reoptimize_YYYY-MM-DD.log", "config/active_config_backup_*.json"],
    artifacts: [
      {
        kind: "log",
        path: "logs/auto_reoptimize_YYYY-MM-DD.log",
        description: "Pipeline log including comparison and promotion/revert decisions."
      }
    ],
    approvalHint: "high_risk"
  },
  {
    name: "daily_automation",
    category: "daily",
    summary: "Run data refresh, plan generation, execution, and dashboard refresh pipeline.",
    commandPreview: "python scripts/daily_automation.py --step all",
    estimatedRuntimeSec: 600,
    reads: ["config/active_config.json", "data/cache/*.parquet", "paper_engine/plans/*.json"],
    writes: ["logs/automation.log", "paper_engine/plans/plan_YYYY-MM-DD.json", "paper_engine/portfolio_state.json"],
    artifacts: [
      {
        kind: "log",
        path: "logs/automation.log",
        description: "Daily automation step logs and summary."
      }
    ],
    approvalHint: "high_risk"
  },
  {
    name: "dashboard_generate_data",
    category: "reporting",
    summary: "Refresh dashboard JSON payloads from latest portfolio, plan, and backtest artifacts.",
    commandPreview: "python dashboard/generate_data.py",
    estimatedRuntimeSec: 60,
    reads: ["paper_engine/portfolio_state.json", "paper_engine/plans/*.json", "journal/*.json"],
    writes: ["dashboard/data/*.json"],
    artifacts: [
      {
        kind: "dashboard_json",
        path: "dashboard/data/*.json",
        description: "Generated dashboard payload files."
      }
    ],
    approvalHint: "safe"
  },
  {
    name: "cli_ingest",
    category: "cli",
    summary: "Refresh/download market data through Atlas CLI.",
    commandPreview: "python scripts/cli.py ingest",
    estimatedRuntimeSec: 900,
    reads: ["config/active_config.json"],
    writes: ["data/cache/*.parquet"],
    artifacts: [],
    approvalHint: "safe"
  },
  {
    name: "cli_universe",
    category: "cli",
    summary: "Build the trading universe through Atlas CLI.",
    commandPreview: "python scripts/cli.py universe",
    estimatedRuntimeSec: 120,
    reads: ["config/active_config.json", "data/cache/*.parquet"],
    writes: ["data/processed/universe.json"],
    artifacts: [
      {
        kind: "report_json",
        path: "data/processed/universe.json",
        description: "Universe tickers and metadata generated by the universe builder."
      }
    ],
    approvalHint: "safe"
  },
  {
    name: "cli_backtest",
    category: "cli",
    summary: "Run the walk-forward backtest via Atlas CLI.",
    commandPreview: "python scripts/cli.py backtest",
    estimatedRuntimeSec: 1200,
    reads: ["config/active_config.json", "data/cache/*.parquet"],
    writes: ["backtest/results/backtest_*.json"],
    artifacts: [
      {
        kind: "metrics_json",
        path: "backtest/results/backtest_*.json",
        description: "Timestamped CLI backtest summary output."
      }
    ],
    approvalHint: "review"
  },
  {
    name: "cli_plan",
    category: "cli",
    summary: "Generate the daily trade plan JSON (approval gate remains separate).",
    commandPreview: "python scripts/cli.py plan [--date YYYY-MM-DD]",
    estimatedRuntimeSec: 300,
    reads: ["config/active_config.json", "data/cache/*.parquet", "paper_engine/portfolio_state.json"],
    writes: ["paper_engine/plans/plan_YYYY-MM-DD.json"],
    artifacts: [
      {
        kind: "plan_json",
        path: "paper_engine/plans/plan_YYYY-MM-DD.json",
        description: "Daily trade plan with proposed/rejected entries and risk summary."
      }
    ],
    args: [
      {
        name: "date",
        type: "string",
        description: "Trade date in YYYY-MM-DD. Defaults to local current date."
      }
    ],
    approvalHint: "review"
  },
  {
    name: "cli_approve",
    category: "cli",
    summary: "Approve a previously generated daily plan.",
    commandPreview: "python scripts/cli.py approve [--date YYYY-MM-DD]",
    estimatedRuntimeSec: 30,
    reads: ["paper_engine/plans/plan_YYYY-MM-DD.json"],
    writes: ["paper_engine/plans/plan_YYYY-MM-DD.json"],
    args: [
      {
        name: "date",
        type: "string",
        description: "Trade date in YYYY-MM-DD."
      }
    ],
    artifacts: [],
    approvalHint: "high_risk"
  },
  {
    name: "cli_paper_run",
    category: "cli",
    summary: "Execute an approved daily paper-trading plan.",
    commandPreview: "python scripts/cli.py paper-run [--date YYYY-MM-DD]",
    estimatedRuntimeSec: 120,
    reads: ["paper_engine/plans/plan_YYYY-MM-DD.json", "paper_engine/portfolio_state.json", "data/cache/*.parquet"],
    writes: ["paper_engine/portfolio_state.json", "journal/trade_ledger.json", "journal/mistake_log.json"],
    args: [
      {
        name: "date",
        type: "string",
        description: "Trade date in YYYY-MM-DD."
      }
    ],
    artifacts: [
      {
        kind: "portfolio_state_json",
        path: "paper_engine/portfolio_state.json",
        description: "Updated paper portfolio state after execution."
      }
    ],
    approvalHint: "high_risk"
  },
  {
    name: "cli_status",
    category: "cli",
    summary: "Print current portfolio/config/data status via Atlas CLI.",
    commandPreview: "python scripts/cli.py status",
    estimatedRuntimeSec: 60,
    reads: ["config/active_config.json", "paper_engine/portfolio_state.json", "data/cache/*.parquet"],
    writes: [],
    artifacts: [],
    approvalHint: "safe"
  },
  {
    name: "cli_ledger",
    category: "cli",
    summary: "Print recent trade ledger summary via Atlas CLI.",
    commandPreview: "python scripts/cli.py ledger [--days N]",
    estimatedRuntimeSec: 30,
    reads: ["journal/trade_ledger.json"],
    writes: [],
    args: [
      {
        name: "days",
        type: "number",
        description: "Trailing days to summarize; defaults to 30."
      }
    ],
    artifacts: [],
    approvalHint: "safe"
  },
  {
    name: "anneal_review",
    category: "research",
    summary: "Run the self-annealing review / hypothesis / experiment cycle.",
    commandPreview: "python scripts/cli.py review",
    estimatedRuntimeSec: 1800,
    reads: ["journal/*.json", "config/active_config.json", "data/cache/*.parquet"],
    writes: ["journal/changelog.json", "config/config_v*.json", "config/active_config.json"],
    artifacts: [
      {
        kind: "report_json",
        path: "journal/changelog.json",
        description: "Annealing cycle changelog and promotion history."
      }
    ],
    approvalHint: "high_risk"
  }
];

export const ATLAS_JOB_NAMES = ATLAS_JOB_CATALOG.map((job) => job.name);
